const mongoose = require('mongoose');

const urlSchema = new mongoose.Schema({
    shortId:{
        type :String,
        require: true,
        unique: true,
    },
    redirectURL:{
        type: String,
        required: true,
    },
    visitHistory: [{timestamp: {type: Number}}],

    //show the url only generated by that particular id/user not the whole urls
    createdBy:{
       type: mongoose.Schema.Types.ObjectId,
       ref: "users",
    }


}, {timestamps: true})

const URL = mongoose.model('url', urlSchema);

module.exports= URL;